name: TryHackMe Update Badge

on:
  schedule:
    # Runs every 24 hours at midnight
    - cron: '0 0 * * *'
  workflow_dispatch: # Allows manual triggering

jobs:
  tryhackme-badge-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: p4p1/tryhackme-badge-workflow@main
        with:
          # REPLACE 'iamthomasss' BELOW WITH YOUR ACTUAL TRYHACKME USERNAME
          username: "iThomas" 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
