name: Update TryHackMe Badge

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight
  workflow_dispatch: # Allows you to click a button to run it manually

jobs:
  update-badge:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Important: Gives permission to save the image to your repo

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Fetch TryHackMe Badge
      uses: DhanushNehru/tryhackme-badge-action-workflow@v1.0
      with:
        image_path: './assets/tryhackme-badge.png'
        # These lines below tell the script to look at the secrets you just made
        username: ${{ secrets.THM_USERNAME }}
        user_id: ${{ secrets.THM_USER_ID }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
